### ISSUE TITLE
Unable to establish connection using Kepware Simulated Server

### ISSUE THREAD

**Issue by Rahul14189** [j3mg/openopc#1]
Hi, 

Thanks for the updated python version of OpenOPC,

I tried to establish connection using Kepware simulated server but i am unable to establish the connection. The error that i receive is,
![image](https://github.com/j3mg/openopc/assets/99563180/b14534ea-7bb8-4f39-b4a5-92a317ce8ed7)

I have tried to establish the connection using below code,
import OpenOPC
opc = OpenOPC.open_client('localhost')

I have tried connect method as well, it gives False,

Have i missed anything in code or any setting at the Kepware Simulator Server !!

**Comment by j3mg** [comment]
The OpenOPC.open_client call connects to the OpenOPC Gateway service and allows OPC communication across a network. The Gateway service needs to be listening on a TCPv4 port which can be checked by running netstat on the command prompt. The Gateway service listening address is normally set to the IP address of the computer with the environment variable OPC_GATE_HOST instead of using localhost.

The error above seems to indicate that the Gateway service is not running or listening on a localhost address. To connect to the Kepware server directly use OpenOPC.client instead on the local machine.

**Comment by Rahul14189** [comment]
Thanks @j3mg for the quick reply, sorry i saw it late!! 
I am able to make connection locally (i.e. when server and client both are on same machine), using  OpenOPC.client.

But my use case is, that Kepware server will be on different machine and client will be on non-window machine. In this case, i am continuously getting error.

I have downgraded the python version and then
at client side,  i checked-out https://github.com/sightmachine/OpenOPC   repository, this is based on python 2.7 version
at server side machine, i have downloaded the source file from https://sourceforge.net/projects/openopc/files/latest/download
and have installed by selecting only server related service. I installed the gateway service using OpenOPCService.exe -install and started it.
This is working fine in my case.

But i have to use latest updated version of python, and in this case when i kept the gateway service at Kepware server side machine same as it is in above case.
And at client side i am using latest version of python, and have installed OpenOPC-DA and pyro5
i am getting the following error:
![image](https://github.com/j3mg/openopc/assets/99563180/69307328-466e-4c1c-be85-f11103519502)

Please correct me, if i am wrong, 
the error suggests that there is mismatch in Pyro version at server and client side machine, i tried to install latest pyro5 at server side machine to matchup with the library version, but it still throws the same error

So i have two questions:
1. Do i have to install the same file from https://sourceforge.net/projects/openopc/files/latest/download and install at server side machine as i did in python 2.7 version case or OpenOPCService.exe is also updated and have to download from somewhere else?
2. Do we need python installed at server side machine or it will be independent of python?

I went through the documentation and found the instruction as,
![image](https://github.com/j3mg/openopc/assets/99563180/bc9ac799-770d-489f-9e45-8de645f60783)

![image](https://github.com/j3mg/openopc/assets/99563180/6a025000-2a96-48c7-b736-66b62d1fb273)

I followed this, but these commands are not executable, i am making some mistake!!

I am trying to access through opc = OpenOPC.open_client('12.41.0.89').
For all client side environment, i have used linux based OS from docker. 

Any suggestions or guide will be highly helpful !!

**Comment by j3mg** [comment]
The server and client must have the same version of Pyro such as version 5 in OpenOPC-DA. The gateway service must be removed, eg OpenOPCService -remove, before installing a different gateway service otherwise the old gateway service might still run.
The console apps, opc and opc-service, are installed when the OpenOPC-DA package is installed from pypi.
I recommend creating a Python 32 bit virtual environment on the server then install OpenOPC-DA with:
  pip install OpenOPC-DA
Then copy the dlls and install the service as per the readme documentation.

**Comment by Rahul14189** [comment]
@j3mg , Thanks for the reply,

I tried multiple scenarios, i am able to establish connection by running OpenOPCService.py in debug mode, and also in --foreforward. But when i start the OpenOPCService using start command, it shows "Starting service zzzOpenOPCService" and i am able to connect using telnet but client side throws error stating,
![image](https://github.com/j3mg/openopc/assets/99563180/15f90129-0a6b-4e10-96ac-d4aef37af54b)
here the port shown is 0.0.0.0 which is done by library itself, the actual ip, i used was different

i am able to connect in debug mode, but it does not work in start mode

**Comment by j3mg** [comment]
The stack trace above is from a Pyro4 version of OpenOPC so my advice is limited.
It’s likely you have not set OPC_GATE_HOST so will revert to 0.0.0.0
When installing the OpenOPC service make sure the command prompt is running in Administrator mode.
Once the service is set up to listen on the correct address, check that the service is listening on the correct address and port with the netstat command.

**Comment by duduyoyo** [comment]
I believe the error 5 is related to DCOM hardening issue by MS. MS changed default authentication to RPC_C_AUTHN_LEVEL_PKT_INTEGRITY which affects a lot of open source projects, like this [one](https://sourceforge.net/p/j-interop/discussion/600729/thread/731d99133f/) in Java. 

You mentioned Kepware server runs in Windows, but client runs in a non-Windows environment. For this reason, you really should  check [this](https://github.com/duduyoyo/WebSocket4OPC) out, since it provides exactly what you are looking for - no worry about DCOM, cross-platform, Python/JavaScript support etc. Cheers!
